%% Plot
figure('Color','w');

contourf(Speed, Torque, eta_rig_map, 30, 'LineColor', 'none');
hold on;
grid on;
box on;

colormap(gca, turbo(256));
caxis([55 80]);

plot(best_eta_rig_speed, best_eta_rig_torque, 'k-o', ...
    'LineWidth', 2, ...
    'MarkerSize', 6, ...
    'MarkerFaceColor', 'w', ...
    'MarkerEdgeColor', 'k', ...
    'DisplayName', 'Best \eta_{rig}');

plot(best_eta_regen_speed, best_eta_regen_torque, '--', ...
    'Color', [1.0 0.0 1.0], ...
    'LineWidth', 2, ...
    'DisplayName', 'Best \eta_{regen}');

plot(peak_rig_speed, peak_rig_torque, 'p', ...
    'MarkerSize', 13, ...
    'MarkerFaceColor', [1.0 1.0 0.0], ...
    'MarkerEdgeColor', 'k', ...
    'LineWidth', 1.2);

plot(peak_regen_speed, peak_regen_torque, 'p', ...
    'MarkerSize', 13, ...
    'MarkerFaceColor', [0.85 0.0 0.0], ...
    'MarkerEdgeColor', 'k', ...
    'LineWidth', 1.2);

text(peak_rig_speed + 130, peak_rig_torque - 7, ...
    sprintf('Peak  \\eta_{rig} = %.1f%%', peak_eta_rig), ...
    'BackgroundColor', 'w', ...
    'EdgeColor', [0.5 0.5 0.5], ...
    'FontWeight', 'bold');

text(peak_regen_speed + 130, peak_regen_torque - 7, ...
    sprintf('Peak  \\eta_{regen} = %.1f%%', peak_eta_regen), ...
    'BackgroundColor', 'w', ...
    'EdgeColor', [0.5 0.5 0.5], ...
    'FontWeight', 'bold');

xlabel('Speed (RPM)');
ylabel('Torque (Nm)');
title('Best-efficiency operating loci within the reliable operating region');

cb = colorbar;
ylabel(cb, '\eta_{rig} (%)');

legend('Location', 'southoutside', 'Orientation', 'horizontal');

xlim([1000 5000]);
ylim([-200 -40]);